"""
Output generators for ZFD pipeline.
"""

import json
import csv
from typing import Dict


def generate_json(result: Dict, output_path: str):
    """Generate JSON output."""
    with open(output_path, 'w', encoding='utf-8') as f:
        json.dump(result, f, indent=2, ensure_ascii=False)


def generate_csv(result: Dict, output_path: str):
    """Generate CSV token table."""
    fieldnames = [
        'token_id', 'eva', 'zfd', 'operator', 'stem', 'suffix',
        'expansion', 'croatian', 'english', 'confidence', 'notes'
    ]

    with open(output_path, 'w', newline='', encoding='utf-8') as f:
        writer = csv.DictWriter(f, fieldnames=fieldnames)
        writer.writeheader()

        for line in result['lines']:
            for token in line:
                writer.writerow({
                    'token_id': token['id'],
                    'eva': token['eva'],
                    'zfd': token['zfd'],
                    'operator': token['operator'] or '',
                    'stem': token['stem'],
                    'suffix': token['suffix'] or '',
                    'expansion': token['expansion'],
                    'croatian': token['croatian'],
                    'english': token['english'],
                    'confidence': token['confidence'],
                    'notes': '; '.join(token['notes'])
                })


def generate_markdown(result: Dict, output_path: str):
    """Generate Markdown report."""
    folio = result['folio']
    diag = result['diagnostics']

    md = []
    md.append(f"# Folio {folio} Decode Report")
    md.append(f"\n**Generated by ZFD Pipeline**\n")

    # Section A: EVA
    md.append("## Section A: Original EVA\n")
    md.append("```")
    for line in result['lines']:
        md.append(" ".join(t['eva'] for t in line))
    md.append("```\n")

    # Section B: ZFD Orthography
    md.append("## Section B: ZFD Orthography\n")
    md.append("```")
    for line in result['lines']:
        md.append(" ".join(t['zfd'] for t in line))
    md.append("```\n")

    # Section C: Shorthand Expansion
    md.append("## Section C: Shorthand Expansion\n")
    for line in result['lines']:
        for t in line:
            md.append(f"- **{t['eva']}** → {t['expansion']}")
    md.append("")

    # Section D: Normalized Croatian
    md.append("## Section D: Normalized Croatian\n")
    for line in result['lines']:
        md.append(" ".join(t['croatian'] for t in line))
    md.append("")

    # Section E: English Translation
    md.append("## Section E: English Translation\n")
    for line in result['lines']:
        english_line = " ".join(t['english'] for t in line)
        md.append(f"> {english_line}")
    md.append("")

    # Section F: Diagnostics
    md.append("## Section F: Diagnostics\n")
    md.append(f"- **Total tokens:** {diag['total_tokens']}")
    md.append(f"- **Known stems:** {diag['known_stems']} ({diag['known_ratio']:.1%})")
    md.append(f"- **Unknown stems:** {diag['unknown_stems']}")
    md.append(f"- **Average confidence:** {diag['average_confidence']}")
    md.append(f"\n**Operator distribution:**")
    for op, count in diag['operator_counts'].items():
        md.append(f"- {op}: {count}")
    md.append(f"\n**Unknown stems (for lexicon review):**")
    md.append(f"```\n{', '.join(diag['unknown_stem_list'])}\n```")

    md.append("\n**Validation checks:**")
    for check, passed in diag['validation'].items():
        status = "✓ PASS" if passed else "✗ FAIL"
        md.append(f"- {check}: {status}")

    with open(output_path, 'w', encoding='utf-8') as f:
        f.write("\n".join(md))
